src/occurrencetobin/occurrencetobin.cpp

Returns error and exits when the total number of periods of event occurrences in input file exceeds that stated in command line argument. This check existed for option 1 format. Introduction of this check for option 2 format.

Introduce period number check for option 2 format

---

src/fmcalc/fmcalc.h
src/fmpolicytctobin/fmpolicytctobin.cpp
src/fmpolicytctocsv/fmpolicytctocsv.cpp
src/include/oasis.h

fm_policyTC struct definition moved to `include/oasis.h`, and removed from individual source files.

Move fm_policyTC struct to common header file

---

src/gulcalc/doit.cpp
src/gulcalc/gulcalc.h
src/gulcalc/main.cpp

Added `int allocRule = -1` to `gulcalopts` struct. Should alloc rule be specified on command line as either 0 or 1, loss stream is used. If alloc rule is not specified on command line (i.e. default value of -1), then item stream is used.
Now see the following output with first 4 bytes showing correct values for loss stream:
```
0000000 0001 0200 0032 0000 e39f 03b5 8365 0000
```

Fix gulcalc stream headers

---

src/crossvalidation/crossvalidation.cpp
src/validatefootprint/validatefootprint.cpp
src/validateoasisfiles/validateoasisfiles.cpp

Re: issue https://github.com/OasisLMF/ktools/issues/112, `areaperil_id` appears to be the problem as this can be either an `unsigned int` or `unsigned long long` depending on a preprocessor directive (`AREAPERIL_TYPE_UNSIGNED_LONG_LONG` in `include/oasis.h`) at compilation time. Introduce conditional statements to alter behaviour in validation executables depending on `areaperil_id` data type.

Check for areaperil_id data type in validation executables

---

src/getmodel/getmodel.cpp
src/getmodel/getmodel.h

Performance change in getmodel from @johanxnilsson 
>**Johan Nilsson:** What I have done is changed the location of where the footprint file is opened or closed. It was previsouly done in each doCf function on each event, but is now done outside of the event loop, and only once. It should remove some overhead of opening/closing the file for each event processed.

Move footprint file open/close to outside of event loop

---

src/getmodel/getmodel.cpp

Error message is now less vague than segmentation fault, and highlights possible differences between vulnerability IDs in items and vulnerability files.

Introduce try-block to catch invalid vulnerability IDs in getmodel

---

src/gulcalc/gulcalc.cpp

Call to `correlatedWriter_()` was absent in the `mode0()` method. This should have meant that only a header would have been written to the fully correlated GUL file. The fact that perfectly reasonable looking data found its way into the fully correlated GUL stream shows how dangerous buffers can be.

Add conditional call to correlated writer function for gul alloc rule 0

---

src/validatevulnerability/validatevulnerability.cpp

Validation requiring all intensity bins to be present now issues a warning rather than an error:
```
Warning: All intensity bins must be present for each vulnerability ID in single peril models:
Warning: Vulnerability ID 1: 29 out of 58 intensity bins present
Warning: Vulnerability ID 2: 29 out of 58 intensity bins present
Warning: Vulnerability ID 3: 29 out of 58 intensity bins present
Warning: Vulnerability ID 4: 29 out of 58 intensity bins present
Warning: Vulnerability ID 5: 29 out of 58 intensity bins present
Warning: Vulnerability ID 6: 29 out of 58 intensity bins present
All checks pass.  Please take note of any warnings.
Maximum value of damage_bin_index = 12
```

Change missing intensity bins error to warning in validatevulnerability for single peril models

---

src/gulcalc/doit.cpp
src/gulcalc/gulcalc.cpp
src/gulcalc/gulcalc.h
src/gulcalc/main.cpp

New alloc rule assigned number 2. This can be changed if desired. Please supply argument `-a2` to try it out.

Add new gulcalc alloc rule where total peril loss = maximum subperil loss

---

src/gulcalc/gulcalc.cpp
src/gulcalc/gulcalc.h

Remove the unnecessary rewriting of `bin_lookup_` and change its type from `map<int, prob_mean>` to `vector<prob_mean>`. This results in a significant improvement in performance of `gulcalc` when alloc rules 1 or 2 are used. @johcarter's  performance test (in `ktest` repo under `periltest2/perftest`) now yields the following:
```
$ bash runtests_tmp.sh 
Alloc rule 0
real	0m1.028s
user	0m0.015s
sys	0m0.012s
Alloc rule 1
real	0m1.733s
user	0m0.712s
sys	0m0.020s
Alloc rule 2
real	0m1.695s
user	0m0.663s
sys	0m0.032s
```

Fix gulcalc performance issues

---

src/leccalc/aggreports.cpp

Conversion from int to `OASIS_FLOAT` performed before variables are multiplied, thus fixing the integer overflow problem.

Fix integer overflow problem in leccalc

---

src/leccalc/aggreports.cpp
src/leccalc/aggreports.h

Losses for Interpolated return periods that exceed largest return period are capped at the loss from the largest return period. For example, if the largest return period is 1000, the following:
```
summary_id,type,return_period,loss
1,1,5000.000000,7945315.000000
1,1,1000.000000,1589063.000000
1,1,500.000000,1082886.000000
```
Turns into:
```
summary_id,type,return_period,loss
1,1,5000.000000,1589063.000000
1,1,1000.000000,1589063.000000
1,1,500.000000,1082886.000000
```

Remove records where interpolated return period loss runs out of bounds in leccalc

---

docs/md/StreamConversionComponents.md
src/gultobin/gultobin.cpp
src/gultobin/main.cpp

As requested, the stream type can now be specified with the `-t` flag. The default stream type is that for the loss stream:
```
$ gultobin -S10 < guls.csv | hexdump | head -1
0000000 0001 0200 000a 0000 03b2 0000 0001 0000
$ gultobin -S10 -t1 < guls.csv | hexdump | head -1
0000000 0001 0100 000a 0000 03b2 0000 0001 0000
$ gultobin -S10 -t2 < guls.csv | hexdump | head -1
0000000 0001 0200 000a 0000 03b2 0000 0001 0000
```
@johcarter I have updated the md documentation. Please feel free to change it and update the pdf and html files before we merge into `develop`.

Add stream type to gultobin

---

src/fmcalc/fmcalc.cpp
src/fmcalc/fmcalcdoit.cpp

Step policies require the TIVs to be read from `coverages.bin`. Prior to this PR, this has only been done for the deprecated item stream. This is now done for the loss stream too.

Implement step policies from loss stream in fmcalc

---

src/getmodel/getmodel.cpp
src/getmodel/getmodel.h

`std::vector` of intensity bin probabilities replaced with `std::map`. This effectively removes intensity bins with zero probability from being looped over when there is uncertainty in the footprint file, saving some execution time.

Improve performance of getmodel

---

src/getmodel/getmodel.cpp

Introduce an escape condition in for loop to ensure that once cumulative probability reaches 1.0, later damage bin indexes are ignored in cases where footprint file does not have hazard intensity uncertainty. The output is now:
```
$ hexdump ./static/footprint.bin.z | head -1
0000000 003a 0000 0000 0000 9c78 cd4d 2eb9 6184
$ echo 1139 | evetobin -n | getmodel | cdftocsv | head -13
event_id,areaperil_id,vulnerability_id,bin_index,prob_to,bin_mean
1139,36,2,1,0.638000,0.000000
1139,36,2,2,0.814000,0.050000
1139,36,2,3,0.902000,0.150000
1139,36,2,4,0.955000,0.250000
1139,36,2,5,0.996000,0.350000
1139,36,2,6,1.000000,0.450000
1139,36,5,1,0.638000,0.000000
1139,36,5,2,0.814000,0.050000
1139,36,5,3,0.902000,0.150000
1139,36,5,4,0.955000,0.250000
1139,36,5,5,0.996000,0.350000 …
```

Remove unrequired lines in getmodel output

---

src/cdftocsv/cdftocsv.cpp

Specifier for areaperil ID changed from `%d` (signed int) to `%u` (unsigned int). This fixes the issue with negative numbers being printed for very large areaperil IDs.

Fix areaperil ID output in cdftocsv

---

src/aalcalc/aalcalc.cpp
src/aalcalc/aalcalc.h

`vec_sample_sum_loss_` has been converted from `std::vector<loss_rec>` to `std::vector<double>`. It now only contains the `sum_of_loss` values. Period weights are applied when `vec_sample_aal_`, `vec_ensemble_aal_` and `vec_analytical_aal_` are filled, rather than when `vec_sample_sum_loss_` is being filled. The maximum exposure value is calculated as `vec_sample_sum_loss_` is filled and stored in `max_exposure_val_`. This leads to a reduction in memory use to around a third of its initial value.

Reduce memory footprint in aalcalc

---

src/summarycalctocsv/summarycalctocsv.cpp

An optional flag `-o` has been introduced to `summarycalctocsv` to output the Sample Event Loss Table (SELT):
```
$ summarycalctocsv -o < summarycalc.bin > summarycalc.csv
```
This flag is compatible with the options that can be currently selected. This ORD flag takes priority over the exposure value flag `-e`. `ImportedNumLocs` is not currently supported as the required input files are not part of the ktools kernel. An issue to address this shall be raised.

Add option to write Sample Event Loss Table (SELT) with summarycalctocsv

---

src/ensembletobin/ensembletobin.cpp
src/ensembletocsv/ensembletocsv.cpp
src/include/oasis.h

The `ensemble.bin` file defines the mappings between sample IDs and ensemble IDs. Both `aalcalc` and `leccalc` now search for this file in the `input/` directory. This has been changed as the file is not a property of the model and can vary between runs, meaning the `input/` directory is a more appropriate location. This also allows for the file to be created dynamically in the complex model wrapper.
The `ensemble.bin` file now contains two columns: `sidx` and `ensemble_id`. Both `aalcalc` and `leccalc` deduce cases where an ensemble consists of multiple samples without using the `sample_id` column. Therefore, this column has been dropped as it is unnecessary. `ensembletobin` will convert the new two-column and legacy three-column `ensemble.csv` files to binary format.

Change ensemble.bin directory and drop sample_id column

---

src/aalcalc/summaryindex.cpp
src/include/oasis.h
src/leccalc/aggreports.cpp
src/leccalc/aggreports.h
src/leccalc/leccalc.cpp
src/leccalc/main.cpp
src/summarycalc/main.cpp
src/summarycalc/summarycalc.cpp
src/summarycalc/summarycalc.h
src/summaryindex/summaryindex.cpp

`leccalc` and `ordleccalc` use a lot of memory when granular outputs with a high number of samples are requested. To reduce the memory footprint, summary index files can be produced with the `-m` option. For example:
```
$ summarycalc -i -m -1 summarycalcoutput.bin
```
will create the summary index file `summarycalcoutput.idx`.
`leccalc` and `ordleccalc` detect the presence of these files in the work directory. If all `summarycalc` output binary files have a corresponding index file, the index files are collated and a master `summaries.idx` file is produced. The `summaries.idx` file features three columns: summary ID; binary file index; and position relative to start of binary file (offset). Additionally, a list of binary files in the order in which they have been indexed (`filelist.idx`) …

Reduce memory footprint of leccalc and ordleccalc

---

src/crossvalidation/crossvalidation.cpp
src/fmprofiletobin/fmprofiletobin.cpp
src/gultobin/gultobin.cpp
src/include/oasis.h
src/kat/kat.cpp
src/randtobin/randtobin.cpp
src/summarycalctobin/summarycalctobin.cpp
src/validatedamagebin/validatedamagebin.cpp
src/validatefootprint/validatefootprint.cpp
src/validateoasisfiles/validateoasisfiles.cpp
src/validatevulnerability/validatevulnerability.cpp

Increasing the precision of `OASIS_FLOAT` from a 4-byte `float` to an 8-byte `double` caused issues when reading in values of this type with the `%f` format specifier. The precision of `OASIS_FLOAT` can now be changed through the definition of the preprocessor macro `OASIS_FLOAT_TYPE_DOUBLE` in `include/oasis.h`. This results in the use of the `%lf` specifier in cases where `OASIS_FLOAT` acts an alias for a `double`.

Define preprocessor macro to set precision of OASIS_FLOAT

---

src/aalcalc/aalcalc.cpp
src/aalcalc/aalcalc.h
src/aalcalc/main.cpp

An optional flag `-o` has been introduced to `aalcalc` to output the Period Average Loss Table (PALT):
```
$ aalcalc -K[output_directory_name] -o > aalcalc.csv
```
As ensembles are not compatible with ORD format at this time, the ensemble file is ignored if this flag is issued on the command line. `SourceNumLocs` is not currently supported as the required input files are not part of the ktools kernel.

Add option to write Period Average Loss Table (PALT) with aalcalc

---

src/eve/main.cpp

The first two command line arguments supplied to `eve` are the process number and total number of processes respectively. If no valid conversion can be performed by `atoi()`, such as when a string of letters is supplied instead of a numeric character, or 0 is supplied as a parameter, a division by zero error can occur when the modulo operator is applied in `eve.cpp:doshuffle()`. Validity checks on these two parameters have been introduced:
```
$ eve 1 10 -t
1
11
21
$ eve 0 invalid_arg -t
FATAL:eve: Invalid value for processno supplied: 0
FATAL:eve: Invalid value for totalprocesses supplied: invalid_arg
```

Add Validity Checks for Process Number and Total Processes Parameters in eve

---

src/aalcalc/aalcalc.cpp
src/aalcalc/aalcalc.h
src/aalcalc/summaryindex.cpp
src/include/oasis.h

Further reductions to `aalcalc`'s memory footprint have been achieved by calculating the mean and standard deviation by period number. Therefore, the memory footprint is reduced from being in the order of the product of the number of periods and the number of samples, to depending on the number of samples only.
Therefore, assuming a float takes 4 bytes of memory, for 100,000 samples and 1,000,000 periods, previous versions of `aalcalc` would use `100,000 * 1,000,000 * 4 bytes = 400E9 bytes = 400 GB` of memory. Following this change, `aalcalc` uses `100,000 * 4 bytes = 400E3 bytes = 400 kB` of memory.

Calculate mean and standard deviation by period number in aalcalc

---

src/aalcalc/summaryindex.cpp

As part of the ktools `v3.6.1` release, `summarycalc` can produce index files. The index file corresponding to each `summarycalc` binary file is detected by `aalcalc`. Should the index file be found, it is used to construct the master index file. Should the index file be missing, the binary file is used to construct the master index file in the same way as before this change. As each binary file is treated as a separate entity when constructing the master index file, the absence of some or all of the corresponding index files is supported.

Use summary index files from summarycalc in aalcalc

---

src/footprinttobin/footprinttobin.cpp
src/footprinttocsv/footprinttocsv.cpp
src/itemtobin/itemtobin.cpp
src/itemtocsv/itemtocsv.cpp

The unsigned integer `areaperil_id` was incorrectly printed out as a signed integer in the conversion from binary to csv formats in `cdftocsv` (see issue [`ktools` issue 193](https://github.com/OasisLMF/ktools/issues/193)). This was fixed in `v3.6.0`. However, the same issue was found when converting footprint and item files. This has been fixed in the following binaries:
- `footprinttobin` (only affected error messages - the conversion process from csv to binary was and still is sound)
- `footprinttocsv`
- `itemtobin`
- `itemtocsv`

Fix areaperil ID output

---

docs/md/DataConversionComponents.md
src/aalcalc/aalcalc.cpp
src/aalcalc/aalcalc.h
src/eltcalc/eltcalc.cpp
src/include/oasis.h
src/leccalc/leccalc.cpp
src/occurrencetobin/occurrencetobin.cpp
src/occurrencetocsv/occurrencetocsv.cpp
src/pltcalc/pltcalc.cpp

As part of the [Open Data Standards](https://github.com/OasisLMF/OpenDataStandards), the Moment Period Loss Table (MPLT), Quantile Period Loss Table (QPLT) and Sample Period Loss Table (SPLT) contain additional `Hour` and `Minute` time fields. To support these, the occurrence file now supports these two additional fields.
If it is desirable to include the `Hour` and `Minute` fields in the binary file, the `-H` argument should be given when creating this file:
```
occurrencetobin -P10000 -H < occurrence.csv > occurrence.bin
```
A flag to signify the presence of these fields is set in the header of the binary file. If the `Hour` and `Minute` fields do not exist in the csv file and the `-H` argument is given, both fields are assigned the value of 0. To allow for backwards compatibility, all …

Support Hour and Minute fields in Occurrence file

---

src/aalcalc/aalcalc.cpp

The `SourceExposure` field has been removed from the Period Average Loss Table (PALT) written by `aalcalc`. The field was incorrectly calculated as the maximum exposure value across all samples for each summary ID.
The `SourceExposure` field is the sum of the Total Insured Value (TIV) from input exposures, which is currently calculated in the exposure summary report. Currently, this report is not part of the ktools kernel.

Remove SourceExposure field from ORD output

---

.gitignore
src/gulcalc/doit.cpp
src/gulcalc/gulcalc.h
src/gulcalc/main.cpp

The command line flag `-m` for setting the execution mode in `gulcalc` has been removed to simplify user input. The effects of the mode flag can be replicated by using the alloc rule flag `-a`. For example, `-m1` (back allocation) can be replicated using alloc rules 1 or 2:
```
$ eve 1 1 | getmodel | gulcalc -S10 -L0 -a1 -i gulcalc_out.bin
$ eve 1 1 | getmodel | gulcalc -S10 -L0 -a2 -i gulcalc_out.bin
```
Classic `gulcalc` output can be achieved by setting an alloc rule of 0 (loss stream) or not setting one at all (deprecated item or coverage stream):
```
$ eve 1 1 | getmodel | gulcalc -S10 -L0 -a0 -i gulcalc_out.bin
$ eve 1 1 | getmodel | gulcalc -S10 -L0 -i gulcalc_out.bin
$ eve 1 1 | getmodel | gulcalc -S10 -L0 -c gulcalc_out.bin
```
The deprecated coverage stream output is …

Remove command line flag for execution mode from gulcalc

---

src/pltcalc/pltcalc.cpp

Quantile losses for the same `event_id` and `summary_id` differed between the Quantile Event Loss Table (QELT) and Quantile Period Loss Table (QPLT). This was because the `ChanceOfLoss` and `MaxLoss` values from the output of `summarycalc` were erroneously included in the calculation of these losses.
The contributions from `ChanceOfLoss` and `MaxLoss` have been removed. The quantile losses between the QELT and QPLT now agree for the same `event_id` and `summary_id`.

Fix quantile losses in Quantile Period Loss Tables (QPLT)

---

src/aalcalc/summaryindex.cpp

It is no longer a requirement for all event IDs to be present in the occurrence file in order to create the summary index files in `aalcalc`. Should an event ID be encountered that does not exist in the occurrence file, only its offset is recorded.

Ignore events that do not exist in occurrence file when creating summary indexes in aalcalc

---

src/katparquet/katparquet.cpp

`katparquet` now sorts Period Loss Tables (PLTs) by period number and then event ID. This is in contrast to its previous behaviour where it sorted PLTs by event ID only. This brings the sorted outputs from `kat` and `katparquet` in line.

Sort Period Loss Tables by period number and then event ID in katparquet

---

ktest/runtests.sh
ktest/runtestsx.sh

When the relevant ktools components are not linked to parquet libraries during compilation, an error message is produced when parquet output is requested. A check for whether parquet libraries have been linked during compilation has been introduced to the build test script. Should the check fail, no parquet output will be requested. As a result, the error messages are effectively suppressed.

Suppress FATAL error messages during build process if parquet libraries have not been linked to binaries

---

src/aalcalc/aalcalc.cpp

Sample subsets should be fixed and non-overlapping. An error in determining the size of the largest subset given the total number of samples has been fixed.
The field name `VarElementVuln` has been corrected. This is only relevant to the csv output.

Fix determination of sample subsets in Average Loss Convergence Table

---

src/aalcalc/aalcalc.cpp

Following the introduction of the Average Loss Convergence Table (ALCT) in ktools v3.9.0 (see PR https://github.com/OasisLMF/ktools/pull/301 for more details) a bug was introduced where the sample loss vector in `aalcalc` would not be resized when sample size is 1 and the ALCT output was not requested on the command line. Under these circumstances, an attempt to write beyond the scope of the vector would be made, which would throw a segmentation fault. The logic behind resizing the sample loss vector has been changed, thus fixing this issue.

Fix resizing of sample loss vector in aalcalc when sample size is 1

---

src/summarycalc/summarycalc.cpp
src/summarycalc/summarycalc.h

Restructuring `summarycalc` has reduced its execution time by up to 20%. This has been achieved through moving the determination of coverage ID to a parent loop and only looping over those summary level outputs requested by the user.

Performance improvements in summarycalc

---

ktest/runtests.sh
ktest/runtestsx.sh

Following the separation of checksums from non-parquet and parquet test outputs into two files in ktools v3.9.0, the potential for missing failures in acceptance tests of non-parquet output was introduced. This has now been fixed through changes in the testing bash scripts.

Fix undetected failures from acceptance tests on non-parquet output

---

src/crossvalidation/crossvalidation.cpp

The `interval_type` column in the damage bin dictionary model file has been deprecated since ktools v3.4.1. As `validatedamagebin` provides a warning should the damage bin dictionary contain the `interval_type` column, there is no need to perform a deprecated format check again in `crossvalidation`. Data is extracted from the first four columns, thus the `interval_type` column is ignored if present.

Remove requirement for deprecated interval_type column in crossvalidation

---

src/leccalc/aggreports.cpp
src/leccalc/aggreports.h
src/leccalc/leccalc.cpp
src/leccalc/leccalc.h

The logic for determining whether headers are written out has been simplified and moved outside of the `aggreports` class, which has aided the readability of the code. Additionally, this has fixed the missing header issue in the Wheatsheaf output, which has been witnessed when the lowest summary ID yields no output (i.e. when all the samples are zero loss).
The `aggreports` class has been refactored and methods have been simplified in an attempt to optimise the code and make it more readable. The determination of a number of variables have been moved to parent functions, including `EPCalc` and `EPType`. The initialisation of the `aggreports` class has been brought outside any loops, reducing overhead, as has the determination of legacy or ORD output. Other minor changes include passing …

Fix missing header in Wheatsheaf output and refactor aggreports class

---

configure.ac

The option to output results in parquet format has been available since v3.8.0. To facilitate the linking of the Arrow Parquet libraries necessary for this, autotools uses `pkg-config`, which has become a prerequisite. Should this package be missing, a misleading error message is displayed, which can be interpreted to point towards the fault lying with the installation of the Arrow Parquet libraries.
A check for `pkg-config` has been introduced to the autotools build system. The new error message is more helpful:
```
checking for pkg-config... no
configure: error: cannot find pkg-config. Please install pkg-config and run ./configure again.
```

Add check for pkg-config in autotools build system

---

src/gulcalc/gulcalc.cpp

With `gulcalc` allocation rule greater than 0, if the sum of losses per sample exceed the TIV, the TIV is split in proportion to the losses. There is no need to do this for the standard deviation (`sidx = -2`) nor for the chance of loss (`sidx = -4`). Therefore, the calculation on these fields has been dropped to bring it in line with that which is currently conducted in `gulpy`.

Bring split TIV calculation in line with gulpy

---

src/leccalc/aggreports.cpp

A leftover condition statement resulted in miscalculation of the maximum return period. The maximum return period is used to determine losses corresponding to user-requested return periods, and as the maximum return period was set at 0, all requested return periods lay beyond this maximum and were not calculated. Removing this conditional has solved the issue.

Remove condition causing empty leccalc/ordleccalc output files when using period weights and user-defined return periods

---

src/pltcalc/pltcalc.cpp

When the sample size is 1, the mean is the loss value of that sample and the standard deviation is 0. The standard deviation in the `pltcalc` output has been set to 0 in this case. This affects the legacy `pltcalc` output and the ORD Moment Period Loss Table (MPLT).

Fix standard deviation for type 2 entries in pltcalc output

---

src/aalcalc/aalcalc.cpp
src/aalcalcmeanonly/aalcalcmeanonly.cpp
src/gulcalc/gulcalc.cpp
src/include/oasis.h
src/leccalc/leccalc.cpp
src/pltcalc/pltcalc.cpp
src/summarycalc/summarycalc.cpp
src/summarycalctocsv/summarycalctocsv.cpp

Sample index (`sidx`) -4 has been reassigned to represent the number of affected risks. Therefore, filters on `sidx = -4` have been removed in `summarycalctocsv`, allowing for the number of affected risks to be included in the output csv file.

Allow number of affected risks to be processed by summarycalctocsv

---

src/footprinttocsv/footprinttocsv.cpp
src/footprinttocsv/main.cpp

With the `-e` flag, a user is able to specify a range of event IDs to output when converting footprint binary files to csv using `footprinttocsv`. Should a range not have been entered, a default was used. This default had minimum and maximum limits of 1 and 999,999,999 respectively. As event IDs that are greater than this maximum limit should be valid, the range has been removed. Therefore, if a range is not requested by the user, all event IDs are now converted from binary to csv and sent to the output.

Remove default range for event IDs in footprinttocsv
